package ink.astrius.create_avionics.net;

import java.util.Arrays;

/**
 * A layer-2 frame, laid out exactly as an Ethernet II frame:
 *
 * <pre>
 *   ┌──────────┬──────────┬───────────┬───────────────┐
 *   │ dst  (6) │ src  (6) │ type  (2) │ payload (n)   │
 *   └──────────┴──────────┴───────────┴───────────────┘
 * </pre>
 *
 * <p>Matching the real layout byte for byte is the point, not decoration.
 * When a Scalar Evolution machine bridges its emulated NIC onto a
 * {@link Medium}, the frames its guest kernel emits are literal Ethernet
 * frames — real ARP, real IP, produced by a real Linux TCP/IP stack. If
 * our own framing were bespoke we would need a translation layer on that
 * boundary; sharing the layout means a bridged frame is simply
 * {@link #parse}d and transmitted as-is, and our synthetic traffic and a
 * guest's genuine traffic coexist on one medium as peers.</p>
 *
 * <h2>Telling ours apart from theirs</h2>
 * <p>That coexistence only works if the two are unambiguously
 * distinguishable, which is what the type field is for. Guest traffic
 * carries the registered EtherTypes its kernel already uses —
 * {@code 0x0800} for IPv4, {@code 0x0806} for ARP, and so on. Everything
 * this mod generates rides {@link #ETHERTYPE_LOCAL} instead, the value
 * IEEE set aside for exactly this purpose, with a one-byte
 * {@code subProtocol} at the head of the payload separating our own
 * users. Inventing a number in registered space would have worked right
 * up until it met real hardware.</p>
 */
public record Frame(MacAddress destination, MacAddress source, int etherType, byte[] payload) {

    /** Bytes before the payload: two addresses and the type field. */
    public static final int HEADER_LENGTH = MacAddress.LENGTH * 2 + 2;

    /**
     * {@code 0x88B5} — "IEEE Std 802 Local Experimental EtherType 1",
     * reserved by the standard for local use and guaranteed never to be
     * assigned to a real protocol. Every frame this mod originates uses
     * it, sub-divided by {@link #subProtocol()}.
     */
    public static final int ETHERTYPE_LOCAL = 0x88B5;

    /** Sub-protocol: an encapsulated ComputerCraft packet, carried verbatim. */
    public static final int SUB_COMPUTERCRAFT = 0x01;

    /** Sub-protocol: rail control and telemetry — signals, stations, discovery. */
    public static final int SUB_RAIL_CONTROL = 0x02;

    public Frame {
        if (etherType < 0 || etherType > 0xFFFF) {
            throw new IllegalArgumentException("ethertype out of range: " + etherType);
        }
    }

    /**
     * Build a frame carrying one of this mod's own sub-protocols.
     *
     * @param destination Target address, or {@link MacAddress#BROADCAST}.
     * @param source      The transmitting endpoint's address.
     * @param subProtocol One of the {@code SUB_*} constants.
     * @param body        Sub-protocol payload.
     * @return The frame, tagged {@link #ETHERTYPE_LOCAL}.
     */
    public static Frame local(final MacAddress destination, final MacAddress source,
                              final int subProtocol, final byte[] body) {
        if (subProtocol < 0 || subProtocol > 0xFF) {
            throw new IllegalArgumentException("sub-protocol out of range: " + subProtocol);
        }
        final byte[] payload = new byte[body.length + 1];
        payload[0] = (byte) subProtocol;
        System.arraycopy(body, 0, payload, 1, body.length);
        return new Frame(destination, source, ETHERTYPE_LOCAL, payload);
    }

    /**
     * Read a frame off the wire.
     *
     * @param bytes A received frame; must be at least {@link #HEADER_LENGTH}.
     * @return The parsed frame.
     */
    public static Frame parse(final byte[] bytes) {
        if (bytes.length < HEADER_LENGTH) {
            throw new IllegalArgumentException("frame shorter than a header: " + bytes.length);
        }
        final MacAddress dst = MacAddress.of(Arrays.copyOfRange(bytes, 0, 6));
        final MacAddress src = MacAddress.of(Arrays.copyOfRange(bytes, 6, 12));
        final int type = ((bytes[12] & 0xFF) << 8) | (bytes[13] & 0xFF);
        return new Frame(dst, src, type, Arrays.copyOfRange(bytes, HEADER_LENGTH, bytes.length));
    }

    /** @return This frame serialised for {@link Medium#transmit}. */
    public byte[] toBytes() {
        final byte[] out = new byte[HEADER_LENGTH + this.payload.length];
        System.arraycopy(this.destination.bytes(), 0, out, 0, MacAddress.LENGTH);
        System.arraycopy(this.source.bytes(), 0, out, MacAddress.LENGTH, MacAddress.LENGTH);
        out[12] = (byte) (this.etherType >> 8);
        out[13] = (byte) this.etherType;
        System.arraycopy(this.payload, 0, out, HEADER_LENGTH, this.payload.length);
        return out;
    }

    /** @return Whether this frame was generated by this mod rather than a bridged guest. */
    public boolean isLocal() {
        return this.etherType == ETHERTYPE_LOCAL;
    }

    /**
     * The sub-protocol of a {@link #isLocal() local} frame.
     *
     * @return One of the {@code SUB_*} constants, or -1 if this is not a
     * local frame or carries no payload.
     */
    public int subProtocol() {
        if (!this.isLocal() || this.payload.length == 0) return -1;
        return this.payload[0] & 0xFF;
    }

    /**
     * The payload of a {@link #isLocal() local} frame, past the
     * sub-protocol byte.
     *
     * @return The sub-protocol's own body.
     */
    public byte[] body() {
        if (!this.isLocal() || this.payload.length == 0) return this.payload.clone();
        return Arrays.copyOfRange(this.payload, 1, this.payload.length);
    }

    /** @return Whether this frame should be accepted by an endpoint at {@code address}. */
    public boolean addressedTo(final MacAddress address) {
        return this.destination.isBroadcast() || this.destination.equals(address);
    }

    @Override
    public boolean equals(final Object o) {
        return o instanceof final Frame f
                && this.etherType == f.etherType
                && this.destination.equals(f.destination)
                && this.source.equals(f.source)
                && Arrays.equals(this.payload, f.payload);
    }

    @Override
    public int hashCode() {
        return 31 * (31 * this.destination.hashCode() + this.source.hashCode())
                + 31 * this.etherType + Arrays.hashCode(this.payload);
    }

    @Override
    public String toString() {
        return "Frame[" + this.source + " -> " + this.destination
                + " type=0x" + Integer.toHexString(this.etherType)
                + (this.isLocal() ? " sub=" + this.subProtocol() : "")
                + " len=" + this.payload.length + "]";
    }
}
